# Based on an issue template from the Discord API documentation.
name: Feature Request
description: Suggestions for new or different behavior in the library
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "Before opening a new issue, please search existing issues: https://github.com/Remora/Remora.Discord/issues?q=is%3Aissue+label%3Aenhancement"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of what the feature request is.
    validations:
      required: true
  - type: textarea
    id: needed
    attributes:
      label: Why This is Needed
      description: Provide a clear and concise explanation of what problem this solves for you.
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternatives Considered
      description: There's usually more than one way to solve a problem. What are some other alternatives you've considered, if any?
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Additional Details
      description: Is there anything else you can add about this feature request?
    validations:
      required: false
