//
//  GuildWidget.cs
//
//  Author:
//       Jarl Gullberg <jarl.gullberg@gmail.com>
//
//  Copyright (c) 2017 Jarl Gullberg
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

using JetBrains.Annotations;
using Remora.Discord.API.Abstractions.Objects;
using Remora.Discord.Core;

namespace Remora.Discord.API.Objects
{
    /// <inheritdoc />
    [PublicAPI]
    public class GuildWidget : IGuildWidget
    {
        /// <inheritdoc />
        public bool IsEnabled { get; }

        /// <inheritdoc />
        public Snowflake? ChannelID { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="GuildWidget"/> class.
        /// </summary>
        /// <param name="isEnabled">Whether the widget is enabled.</param>
        /// <param name="channelID">The channel invites generated by this widget leads to.</param>
        public GuildWidget(bool isEnabled, Snowflake? channelID)
        {
            this.IsEnabled = isEnabled;
            this.ChannelID = channelID;
        }
    }
}
