<Project Sdk="Remora.Sdk">

    <PropertyGroup>
        <VersionPrefix>2026.2</VersionPrefix>
        <Description>Metapackage for Remora.Discord's various components</Description>
        <PackageReleaseNotes>
            Update SDK and dependencies.
            BREAKING: add cancellation token to CacheService.TryGetPreviousValueAsync
            update correct property in SetDefaultEvictionExpiration
            evict message when its reactions are updated
            BREAKING: Implement new fields on MESSAGE_REACTION_ADD and MESSAGE_REACTION_REMOVE
            add handle null to HeartbeatConverter
            BREAKING: make channel application_id nullable
        </PackageReleaseNotes>

        <!-- No need for build output, since this is a metapackage -->
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <NoPackageAnalysis>true</NoPackageAnalysis>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Backend\Remora.Discord.Caching\Remora.Discord.Caching.csproj" />
      <ProjectReference Include="..\Remora.Discord.Commands\Remora.Discord.Commands.csproj" />
      <ProjectReference Include="..\Remora.Discord.Extensions\Remora.Discord.Extensions.csproj" />
      <ProjectReference Include="..\Remora.Discord.Hosting\Remora.Discord.Hosting.csproj" />
      <ProjectReference Include="..\Remora.Discord.Interactivity\Remora.Discord.Interactivity.csproj" />
      <ProjectReference Include="..\Remora.Discord.Pagination\Remora.Discord.Pagination.csproj" />
    </ItemGroup>

</Project>
