@startuml
'https://plantuml.com/activity-diagram-beta

start

:Message or Interaction Event Received;
:Prepare Command (A);
if (IsSuccess) is (true) then
    :Run Pre-Execution Events (A);
    :Execute Prepared Command (A);
    :Run Post-Execution Events (A);
else (false)
    :Run Preparation Error Events (A);
endif

stop

@enduml
